pipeline {
    agent any
    
    stages {
        stage('Remove Backend Container') {
            steps {
                script {
                    def backendExists = sh(script: 'docker ps -a --format "{{.Names}}" | grep -q "backend" && echo "true" || echo "false"', returnStdout: true).trim()

                    if (backendExists == 'true') {
                        sh 'docker rm -f backend'
                    }
                }
            }
        }
        stage('Remove Backend Image') {
            steps {
                script {
                    def backendExists = sh(script: 'docker images -q backend', returnStatus: true)

                    if (backendExists == 'true') {
                        sh 'docker rmi -f backend'
                    }
                }
            }
        }
        stage('Backend Build') {
            steps {
                dir('Backend/moass-api-server') {
                    def backendExists = sh(script: 'docker ps -a --format "{{.Names}}" | grep -q "backend" && echo "true" || echo "false"', returnStdout: true).trim()

                    if (backendExists == 'true') {
                        sh 'docker rm -f backend'
                    }

                    sh 'docker rmi backend'
                    sh 'docker build --no-cache -t backend .'
                }
            }
        }
    }
    
    post {
        success {
            // 성공적으로 빌드 및 테스트 완료 시 수행할 작업
            echo 'Build and tests passed successfully!'
        }
        failure {
            // 빌드 또는 테스트 실패 시 수행할 작업
            echo 'Build or tests failed!'
        }
    }
}
