pipeline {
    agent any
    
    stages {
        stage('Backend Build') {
            steps {
                dir('Backend/moass-api-server') {
                    sh 'docker build -t backend .'
                    sh 'docker image prune'
                }
            }
        }
    }
    
    post {
        success {
            // 성공적으로 빌드 및 테스트 완료 시 수행할 작업
            echo 'Build and tests passed successfully!'
        }
        failure {
            // 빌드 또는 테스트 실패 시 수행할 작업
            echo 'Build or tests failed!'
        }
    }
}
