//@baseUrl = http://localhost:8080/api
@baseUrl = https://k10e203.p.ssafy.io/api

@baseday = {{ $uuid.timestamp("yyyy-MM-dd") }}


###
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "userEmail": "master@com",
  "password": "1234"
}

> {%
    client.global.set("masterAccessToken", response.body.data.accessToken);
    client.log(client.global.get("masterAccessToken"))

    // 날짜 포맷 및 날짜 계산을 위한 보조 함수
    function pad(n) { return n < 10 ? '0' + n : n; }

    // 주어진 일수를 오늘 날짜에 더하는 함수
    function addDaysToDate(days) {
        var today = new Date(); // 오늘 날짜를 기준으로 설정
        today.setDate(today.getDate() + days); // 일수를 더함

        var year = today.getFullYear();
        var month = pad(today.getMonth() + 1); // 월은 0에서 시작하므로 1을 더해줍니다.
        var day = pad(today.getDate());

        return year + '-' + month + '-' + day; // yyyy-MM-dd 형식으로 반환
    }
    client.global.set("today", addDaysToDate(0)); // 오늘 날짜
    client.global.set("today2", addDaysToDate(2)); // 2일 후
    client.global.set("today3", addDaysToDate(3)); // 3일 후
    client.global.set("today4", addDaysToDate(4)); // 4일 후
    client.global.set("today5", addDaysToDate(5)); // 5일 후
    client.global.set("today6", addDaysToDate(6)); // 6일 후
    client.global.set("today7", addDaysToDate(7)); // 7일 후

    client.log("Today + 2 days: " + client.global.get("today2"));
    client.global.set("addDaysToDate", addDaysToDate);
%}

<> 2024-05-07T141902.200.json
<> 2024-05-07T141512.200.json
<> 2024-05-07T141329.200.json
<> 2024-05-07T141224.200.json
<> 2024-05-07T141204.200.json
<> 2024-05-07T141057.200.json
<> 2024-05-07T141033.200.json
<> 2024-05-07T140931.200.json

###
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "userEmail": "Z001@com",
  "password": "1234"
}

> {%
    client.global.set("accessToken1", response.body.data.accessToken);
    client.log(client.global.get("accessToken1"))
%}

<> 2024-05-07T141903.200.json
<> 2024-05-07T141512-1.200.json
<> 2024-05-07T141329-1.200.json

###
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "userEmail": "Z002@com",
  "password": "1234"
}

> {%
    client.global.set("accessToken2", response.body.data.accessToken);
    client.log(client.global.get("accessToken2"))
%}

<> 2024-05-07T141903-1.200.json
<> 2024-05-07T141512-2.200.json
<> 2024-05-07T141329-2.200.json

###
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "userEmail": "Z011@com",
  "password": "1234"
}

> {%
    client.global.set("accessToken11", response.body.data.accessToken);
    client.log(client.global.get("accessToken11"))
%}

<> 2024-05-07T141903-2.200.json
<> 2024-05-07T141512-3.200.json
<> 2024-05-07T141329-3.200.json

###
POST {{baseUrl}}/reservation
Authorization: Bearer {{masterAccessToken}}
Content-Type: application/json

{
  "classCode":"Z1",
  "category":"board",
  "timeLimit":2,
  "reservationName":"플립보드1" ,
  "colorCode":"#110101"
}

<> 2024-05-07T141903-3.200.json
<> 2024-05-07T141512-4.200.json
<> 2024-05-07T141330.200.json
<> 2024-05-07T140911-4.200.json

###
POST {{baseUrl}}/reservation
Authorization: Bearer {{masterAccessToken}}
Content-Type: application/json

{
  "classCode":"Z1",
  "category":"meeting",
  "timeLimit":3,
  "reservationName":"팀미팅" ,
  "colorCode":"#123215"
}

<> 2024-05-07T141903-4.200.json
<> 2024-05-07T141513.200.json
<> 2024-05-07T141330-1.200.json
<> 2024-05-07T140911-5.200.json

###
POST {{baseUrl}}/reservationinfo
Authorization: Bearer {{accessToken1}}
Content-Type: application/json

{
  "reservationId":1,
  "infoName":"가나다라",
  "infoTimes":[1,4],
  "infoDate": "{{today3}}" ,
  "infoUsers":["9000001","9000002","9000003"]
}

<> 2024-05-07T141904.200.json
<> 2024-05-07T141513-1.200.json
<> 2024-05-07T141330-2.200.json
<> 2024-05-07T141245.200.json
<> 2024-05-07T140911.400.json

###
POST {{baseUrl}}/reservationinfo
Authorization: Bearer {{accessToken1}}
Content-Type: application/json

{
  "reservationId":1,
  "infoName":"가나다라",
  "infoTimes":[3,4],
  "infoDate":"{{today}}",
  "infoUsers":["9000001","9000003"]
}

<> 2024-05-07T141904-1.200.json
<> 2024-05-07T141513-2.200.json
<> 2024-05-07T141330.400.json
<> 2024-05-07T141241.400.json
<> 2024-05-07T140912.400.json

###
POST {{baseUrl}}/reservationinfo
Authorization: Bearer {{accessToken1}}
Content-Type: application/json

{
  "reservationId":1,
  "infoName":"가나다라",
  "infoTimes":[7,8],
  "infoDate":"{{today5}}",
  "infoUsers":["9000001","9000002","9000003","9000004","9000005"]
}

<> 2024-05-07T141905.200.json
<> 2024-05-07T141513-3.200.json
<> 2024-05-07T141410.200.json
<> 2024-05-07T141330.500.json
<> 2024-05-07T140912-1.400.json

###
POST {{baseUrl}}/reservationinfo
Authorization: Bearer {{accessToken2}}
Content-Type: application/json

{
  "reservationId":1,
  "infoName":"가나다라",
  "infoTimes":[7,8],
  "infoDate":"{{today4}}",
  "infoUsers":["9000001","9000002","9000003","9000004","9000005"]
}

<> 2024-05-07T141905-1.200.json
<> 2024-05-07T141513-4.200.json
<> 2024-05-07T141330-1.400.json
<> 2024-05-07T140912-2.400.json

###
POST {{baseUrl}}/reservationinfo
Authorization: Bearer {{accessToken11}}
Content-Type: application/json

{
  "reservationId":1,
  "infoName":"가나다라",
  "infoTimes":[13,15],
  "infoDate":"{{today}}",
  "infoUsers":["9000011","9000012"]
}

<> 2024-05-07T141906.200.json
<> 2024-05-07T141513-5.200.json
<> 2024-05-07T141330.401.json
<> 2024-05-07T140912.401.json

###
POST {{baseUrl}}/reservationinfo
Authorization: Bearer {{accessToken11}}
Content-Type: application/json

{
  "reservationId":2,
  "infoName":"가나다라",
  "infoTimes":[13,14],
  "infoDate":"{{today}}",
  "infoUsers":["9000011","9000012"]
}

<> 2024-05-07T141906-1.200.json

###
POST {{baseUrl}}/reservationinfo
Authorization: Bearer {{accessToken2}}
Content-Type: application/json

{
  "reservationId":2,
  "infoName":"가나라",
  "infoTimes":[1,3],
  "infoDate":"{{today2}}",
  "infoUsers":["9000001","9000003","9000004","9000005"]
}

<> 2024-05-07T141906-2.200.json