pipeline {
    agent any

    stages {
        stage('Embedded Build') {
	        steps {
				dir('Embedded/electron-app') {
                    sh 'docker build --no-cache -t dongho416/embedded:test .'
                    sh '''
                        docker rmi -f $(docker images -f "dangling=true" -q)
                    '''
                    sh 'docker push -f dongho416/embedded:test'
                }
            }
        }
    }
}
